joint1_controller:
  type: effort_controllers/JointEffortController
  joint: joint1
joint2_controller:
  type: effort_controllers/JointEffortController
  joint: joint2
joint3_controller:
  type: effort_controllers/JointEffortController
  joint: joint3
joint4_controller:
  type: effort_controllers/JointEffortController
  joint: joint4
joint5_controller:
  type: effort_controllers/JointEffortController
  joint: joint5
joint6_controller:
  type: effort_controllers/JointEffortController
  joint: joint6
joint7_controller:
  type: effort_controllers/JointEffortController
  joint: joint7
joint8_controller:
  type: effort_controllers/JointEffortController
  joint: joint8

